from typing import Any


def generate_report(state: dict[str, Any]) -> str:
    """Generate a structured Markdown research report from agent state."""
    lines = []
    lines.append("# Quantitative Research Report")
    lines.append(
        f"\n**Objective:** {state.get('research_objective', 'N/A')}"
    )
    lines.append(f"\n## Hypothesis\n{state.get('hypothesis', 'N/A')}")

    lines.append("\n## Strategy Code\n```python")
    lines.append(state.get("strategy_code", "# No strategy generated"))
    lines.append("```")

    bt = state.get("backtest_results", {})
    lines.append("\n## Backtest Results\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Avg Return | {bt.get('avg_return', 0):.2f}% |")
    lines.append(f"| Avg Sharpe | {bt.get('avg_sharpe', 0):.2f} |")
    lines.append(
        f"| Avg Max Drawdown | {bt.get('avg_max_drawdown', 0):.2f}% |"
    )
    lines.append(
        f"| Total Return | {bt.get('total_return_pct', 0):.2f}% |"
    )

    risk = state.get("risk_metrics", {})
    lines.append("\n## Risk Assessment\n")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(
        f"| Calmar Ratio | {risk.get('calmar_ratio', 0):.2f} |"
    )
    lines.append(f"| Risk Flag | {risk.get('risk_flag', 'N/A')} |")
    lines.append(
        f"| Drawdown Flag | {risk.get('drawdown_flag', 'N/A')} |"
    )

    critique = state.get("critique", {})
    lines.append("\n## Critique")
    if critique:
        for key, value in critique.items():
            lines.append(f"- **{key}:** {value}")
    else:
        lines.append("No critique provided.")

    lines.append("\n---")
    lines.append("*Generated by Aurelion Quant Research Agent*")

    return "\n".join(lines)
